graph,simplification

diff --git a/breakpoint_graph/breakpoint_graph_simple_SVs b/breakpoint_graph/breakpoint_graph_simple_SVs
--- a/breakpoint_graph/breakpoint_graph_simple_SVs
+++ b/breakpoint_graph/breakpoint_graph_simple_SVs
@@ -114,20 +114,17 @@ if [[ $cn_norm == "" ]] || [[ ! -s $cn_norm ]];then
         exit 1
 fi
 echo "cn_norm_germ = ${cn_norm_germ}"
-if [[ $mode == "somatic" ]];then
-	if [[ $cn_norm_germ == "" ]];then
-		echo "cn_norm_germ directory is required";
-		exit 1
-	fi
-        if [[ $germ_LocSeq_result == "" ]];then
-                echo "germ_LocSeq_result is required";
-                exit 1
-        fi
-fi
 echo "out_dir = ${out_dir}"
 
 bin="$cn_norm/"
 normal_bin="$cn_norm_germ/"
+if [[ $mode == "somatic" ]];then
+        if [[ $cn_norm_germ == "" ]];then
+                echo "cn_norm_germ directory is required";
+                exit 1
+        fi
+fi
+
 if [[ -s $out_dir ]];then
 	echo "The breakpoint graph exists... simplifying"
 else
